apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}-admin
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admin
spec:
  replicas: {{ .Values.admin.replicaCount }}
  selector:
    matchLabels:
      {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: admin
  template:
    metadata:
      labels:
        {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: admin
    spec:
      {{- if .Values.admin.affinity }}
      affinity: {{- toYaml . | nindent 12 }}
      {{- end }}
      {{- with .Values.admin.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: admin
        image: {{ include "api.image" . }}
        imagePullPolicy: {{ .Values.admin.image.pullPolicy }}
        command: [ "uvicorn", "service.entrypoints.admin:app", "--host", "0.0.0.0", "--port", "{{ .Values.admin.service.port }}", "--log-level", "info" ]
        env:
          {{- include "env" . | nindent 10 }}
        ports:
          - name: http
            containerPort: {{ .Values.admin.service.port }}
            protocol: TCP
        {{- if .Values.admin.resources }}
        resources: {{- toYaml . | nindent 12 }}
        {{- end }}
        readinessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: http
          periodSeconds: 1
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 15
