apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-admin
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: admin
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.admin.service.port }}
      targetPort: {{ .Values.admin.service.port }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: admin
