version: "3.7"

services:
  postgresql:
    image: postgres:15.6
    hostname: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - web
    restart: always
  api:
    image: "huscker/profanity-filter-docker:latest"
    pull_policy: always
    ports:
      - "8000:8000"
    command: |
      poetry run uvicorn service.entrypoints.api:app --host 0.0.0.0 --port 8000 --log-level info
    depends_on:
      - postgresql
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: always
    networks:
      - web
  admin:
    image: "huscker/profanity-filter-docker:latest"
    pull_policy: always
    ports:
      - "8000:8000"
    command: |
      poetry run uvicorn service.entrypoints.admin:app --host 0.0.0.0 --port 8000 --log-level info
    depends_on:
      - postgresql
    environment:
      - POSTGRES_HOST=postgresql
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
    restart: always
    networks:
      - web
networks:
  web:
volumes:
  postgres_data:
