site_name: Profanity filter
site_description: Project documentation on profanity filter service.
edit_uri: blob/master/docs/
nav:
  - Home: index.md
  - 'User guide':
      - Installation: user-guide/installation.md
  - 'Developer guide':
      - Installation: developer-guide/installation.md
      - Extending functionality: developer-guide/adding-providers.md
theme: readthedocs
