apiVersion: v2
name: profanity-filter-docker
description: A Helm chart for deploying profanity filter service
type: application
version: 0.1.1
appVersion: "0.1.1"
kubeVersion: ">= 1.27.0"
keywords:
- profanity
maintainers:
- name: Egor Golubev
  email: egostalker03@mail.ru
  url: https://github.com/huscker/profanity-filter-docker
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 11.9.13
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
