name: Main Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -t ghcr.io/huscker/profanity-filter-docker:latest
    - name: Push newly built docker image
      run: docker push ghcr.io/huscker/profanity-filter-docker:latest
