name: Release (docs)

on:
  push:
    branches: ["master"]

jobs:
  test_linting:
    runs-on: ubuntu-latest
    steps:
      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.11.0

      - name: Initialize devbox
        run: devbox init

      - name: Install dependencies
        run: devbox run install

      - name: Run pre-commit checks
        run: devbox run mkdocs gh-deploy
